name: tickets_ingresos
description: "Tickets Ingreso"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  audioplayers: ^6.5.1
  shared_preferences: ^2.2.2
  injectable: ^2.5.1
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/

  fonts:
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
